using System;
using Newtonsoft.Json;

namespace AttributesDemo
{
    [JsonObject(MemberSerialization = MemberSerialization.Fields)]
    public class AuthorJsonObjectFields
    {
        private string privateField;

        [JsonProperty]
        private string privateFieldWithAttribute;

        [JsonProperty]
        public string name { get; set; }

        public string[] courses { get; set; }

        public DateTime since;

        [NonSerialized]
        public bool happy;

        [JsonIgnoreAttribute]
        public object issues { get; set; }

        private double salary { get; set; }

        public string IsAutoGeneratedProp { get; set; }

        [JsonPropertyAttribute(DefaultValueHandling = DefaultValueHandling.Include)]
        public string NotAutoGenerated
        {
            get
            {
                return privateField;
            }
            set
            {
                privateField = value;
            }
        }

    }
}
