using System;
using Newtonsoft.Json;

namespace AttributesDemo
{
    [JsonObject(MemberSerialization = MemberSerialization.OptOut)]
    public class AuthorJsonObjectOptOut
    {
        private string privateField;

        [JsonProperty]
        private string privateFieldWithAttribute;

        [JsonProperty]
        public string name { get; set; }

        public string[] courses { get; set; }

        public DateTime since;

        [NonSerialized]
        public bool happy;

        [JsonIgnoreAttribute]
        public object issues { get; set; }

        private string NotAutoGeneratedProperty
        {
            get
            {
                return privateField;
            }
            set
            {
                privateField = value;
            }
        }
    }
}
