using System;
using Newtonsoft.Json;

namespace AttributesDemo
{
    class JsonOptInOptOutDemo
    {
        /// <summary>
        /// OptIn, OptOut, and Fields
        /// </summary>
        public static void Show()
        {
            Console.Clear();
            Console.WriteLine("*** Json OptIn & OptOut ***");

            Console.WriteLine("- OptIn");
            AuthorJsonObjectOptIn xavierAuthorOptIn = new AuthorJsonObjectOptIn()
            {
                name = "Xavier Morera",
                courses = new string[] { "Solr", "Spark", "Python" },
                since = DateTime.Now
            };
            string xavierJsonOptIn = JsonConvert.SerializeObject(xavierAuthorOptIn, Formatting.Indented);
            Console.WriteLine(xavierJsonOptIn);

            Console.WriteLine("- OptOut");
            AuthorJsonObjectOptOut xavierAuthorOptOut = new AuthorJsonObjectOptOut()
            {
                name = "Xavier Morera",
                courses = new string[] { "Solr", "Spark", "Python" },
                since = DateTime.Now
            };
            string xavierJsonOptOut = JsonConvert.SerializeObject(xavierAuthorOptOut, Formatting.Indented);
            Console.WriteLine(xavierJsonOptOut);

            Console.WriteLine("- Fields");
            AuthorJsonObjectFields xavierAuthorFields = new AuthorJsonObjectFields()
            {
                name = "Xavier Morera",
                courses = new string[] { "Solr", "Spark", "Python" },
                since = DateTime.Now,
                IsAutoGeneratedProp = "Value for auto generated",
                NotAutoGenerated = "Value for NOT auto generated"
            };
            string xavierJsonFields = JsonConvert.SerializeObject(xavierAuthorFields, Formatting.Indented);
            Console.WriteLine(xavierJsonFields);
        }
    }
}
